
### The following functions borrow heavily from this gist by @jnolis
### https://gist.github.com/jnolis/a41c196a5e22e2a2115d28e853d4780c
### Unfortunately, the shiny app framework didn't work for me
### So I created an interactive console script that guides you through authentification
### No shiny needed

# This function creates a URL for users to click to authenticate.
# You should use it to show a URL when users haven't authenticated yet.
get_authorization_url <- function(app, permission=NULL){
  private_key <- NULL
  response <- httr::POST("https://api.twitter.com/oauth/request_token", 
                         oauth_sig("https://api.twitter.com/oauth/request_token",
                                   "POST", private_key = NULL, oauth_callback = "oob", app = app))
  httr::stop_for_status(response)
  params <- httr::content(response, type = "application/x-www-form-urlencoded")
  authorize_url <- httr::modify_url("https://api.twitter.com/oauth/authenticate",
                                    query = list(oauth_token = params$oauth_token, permission = permission))
  
  fin <-
    list(
      authorize_url = authorize_url,
      oauth_token = params$oauth_token,
      oauth_token_secret = params$oauth_token_secret
    )
  
  
  return(fin)
  
}




# This function takes the auth token and verifier to create the final access token and secret
get_access_token <- function(app, oauth_token, oauth_verifier){
  url <- paste0("https://api.twitter.com/oauth/access_token?oauth_token=",
                oauth_token,"&oauth_verifier=",oauth_verifier)
  response <- httr::POST(url, 
                         oauth_sig(url,
                                   "POST",
                                   private_key = NULL))
  if(response$status_code == 200L){
    results <- httr::content(response,type="application/x-www-form-urlencoded", encoding="UTF-8")
    
    results[["screen_name"]] <- NULL # since storing that might be creepy
    results[["user_id"]] <- NULL     # since storing that might be creepy
    
    results
  } else {
    NULL
  }
}

# this is a modification of Michael's code to make the signature for authenticating twitter
# API requests. It's pulled from tokens.R in the rtweet package
oauth_sig <- function(url, method,
                      token = NULL,
                      token_secret = NULL,
                      private_key = NULL, 
                      app = NULL,
                      ...) {
  httr::oauth_header(httr::oauth_signature(url, method, app, token,
                                           token_secret, private_key, other_params = list(...)))
}

auth_bot <- function(consumer_key, consumer_secret){
  
  # The app we'll be using. I didn't give it a name since it doesn't seem to matter
  app <- httr::oauth_app(
    app = "",
    key = consumer_key,
    secret = consumer_secret
  )
  
  usethis::ui_done("Credentials set.")
  
  usethis::ui_info("IMPORTANT: Make sure you are logged in with your main Twitter account (which has Twitter Developer access).")
  
  go_on <- usethis::ui_yeah("Did you do that?", 
                            yes = c("Yes", "Absolutely", "100%"),
                            no = c("What?", "No", "No. No. No."))
  
  if(go_on){
    con <- get_authorization_url(app)
    
    usethis::ui_todo("Perfect. Now log in to your bot account.")
    
    usethis::ui_todo("Paste the following link into your browser:")
    usethis::ui_line(con$authorize_url)
    
    if (clipr::clipr_available()) {
      clipr::write_clip(con$authorize_url)
      message("Link copied to your clipboard.")
    }
    
    usethis::ui_todo('Click on "Authorize App"')
    usethis::ui_todo("After clicking on that, you should see an autogenerated 7 digit number.")
    usethis::ui_todo("Type in that number now and hit [ENTER]")
    
    oauth_verifier <- readline()
    
    
    access_token <- get_access_token(app, con$oauth_token, oauth_verifier)
    
    if(is.null(access_token)){
      usethis::ui_oops("Failure. Something went wrong. Try again.")
      stop()
      
    } else{
      usethis::ui_done("Success. Your access code token and secret are ready:")
      
      usethis::ui_code(paste0("access_token=", access_token$oauth_token))
      usethis::ui_code(paste0("access_secret=", access_token$oauth_token_secret))
      
      message("Make sure to note them down somewhere!")
      
    }    
  }
  
}


### Just Run this function with your main account consumer key and secret
### In my case I saved both of those values in my environment
### But you can loa them in however you want
auth_bot(Sys.getenv("consumer_key"), Sys.getenv("consumer_secret"))

